--------------------
2018-08-23 15:32:20 - Exception on message: {}:
Traceback (most recent call last):
  File "/Users/Helen/karelia/example.py", line 24, in <module>
    message = bot.parse()
  File "/Users/Helen/karelia/karelia.py", line 220, in parse
    packet = Packet(**incoming)
TypeError: type object argument after ** must be a mapping, not str


--------------------
2018-08-23 15:32:22 - Exception on message: {}:
Traceback (most recent call last):
  File "/Users/Helen/karelia/example.py", line 24, in <module>
    message = bot.parse()
  File "/Users/Helen/karelia/karelia.py", line 220, in parse
    packet = Packet(**incoming)
TypeError: type object argument after ** must be a mapping, not str


--------------------
2018-08-23 15:32:24 - Exception on message: {}:
Traceback (most recent call last):
  File "/Users/Helen/karelia/example.py", line 24, in <module>
    message = bot.parse()
  File "/Users/Helen/karelia/karelia.py", line 220, in parse
    packet = Packet(**incoming)
TypeError: type object argument after ** must be a mapping, not str


--------------------
2018-08-23 15:32:26 - Exception on message: {}:
Traceback (most recent call last):
  File "/Users/Helen/karelia/example.py", line 24, in <module>
    message = bot.parse()
  File "/Users/Helen/karelia/karelia.py", line 220, in parse
    packet = Packet(**incoming)
TypeError: type object argument after ** must be a mapping, not str


--------------------
2018-08-23 15:32:28 - Exception on message: {}:
Traceback (most recent call last):
  File "/Users/Helen/karelia/example.py", line 24, in <module>
    message = bot.parse()
  File "/Users/Helen/karelia/karelia.py", line 220, in parse
    packet = Packet(**incoming)
TypeError: type object argument after ** must be a mapping, not str


--------------------
2018-08-23 15:33:57 - Exception on message: {}:
Traceback (most recent call last):
  File "/Users/Helen/karelia/example.py", line 24, in <module>
    message = bot.parse()
  File "/Users/Helen/karelia/karelia.py", line 220, in parse
    packet = Packet(**incoming)
  File "/Users/Helen/karelia/karelia.py", line 23, in __init__
    if is_instance(v, dict):
NameError: name 'is_instance' is not defined


--------------------
2018-08-23 15:33:59 - Exception on message: {}:
Traceback (most recent call last):
  File "/Users/Helen/karelia/example.py", line 24, in <module>
    message = bot.parse()
  File "/Users/Helen/karelia/karelia.py", line 220, in parse
    packet = Packet(**incoming)
  File "/Users/Helen/karelia/karelia.py", line 23, in __init__
    if is_instance(v, dict):
NameError: name 'is_instance' is not defined


--------------------
2018-08-23 15:35:08 - Exception on message: <karelia.Packet object at 0x120b362e8>:
Traceback (most recent call last):
  File "/Users/Helen/karelia/example.py", line 25, in <module>
    print(message.keys())
AttributeError: 'Packet' object has no attribute 'keys'


--------------------
2018-08-23 15:35:10 - Exception on message: <karelia.Packet object at 0x120b365c0>:
Traceback (most recent call last):
  File "/Users/Helen/karelia/example.py", line 25, in <module>
    print(message.keys())
AttributeError: 'Packet' object has no attribute 'keys'


--------------------
2018-08-23 15:35:12 - Exception on message: <karelia.Packet object at 0x120b367f0>:
Traceback (most recent call last):
  File "/Users/Helen/karelia/example.py", line 25, in <module>
    print(message.keys())
AttributeError: 'Packet' object has no attribute 'keys'


--------------------
2018-08-23 15:35:14 - Exception on message: <karelia.Packet object at 0x120b36a20>:
Traceback (most recent call last):
  File "/Users/Helen/karelia/example.py", line 25, in <module>
    print(message.keys)
AttributeError: 'Packet' object has no attribute 'keys'


--------------------
2018-08-23 15:35:23 - Exception on message: <karelia.Packet object at 0x120b352e8>:
Traceback (most recent call last):
  File "/Users/Helen/karelia/example.py", line 25, in <module>
    print(message.keys)
AttributeError: 'Packet' object has no attribute 'keys'


--------------------
2018-08-23 15:35:25 - Exception on message: <karelia.Packet object at 0x120b355c0>:
Traceback (most recent call last):
  File "/Users/Helen/karelia/example.py", line 25, in <module>
    print(message.keys)
AttributeError: 'Packet' object has no attribute 'keys'


